function Genlib(filename,options)
arguments
filename = 'Hckt.lib';
options.magnitude = 'p';
options.ComponentLib = ["E_A_LC","hopping_C","hopping_minusC","hopping_minusC_DM"];
options.ModulesLib = [];
options.PlugIns = [];
options.WorkingArea {mustBeMember(options.WorkingArea,{'realTB','realTB_OPAMP','nonH','Sigma_SOI','Chern_M1','Chern_M2'})}= 'realTB';
options.OPAMP = '';
options.ErrorMode = false;
options.Error = 0;
end
magnitude = options.magnitude;
switch  options.WorkingArea
case 'realTB'
ComponentLib  = ["E_A_LC","hopping_C","hopping_minusC","hopping_minusC_DM"];
ModulesLib = options.ModulesLib ;
PlugIns = options.PlugIns ;
case 'realTB_OPAMP'
ComponentLib  = ["E_A_LC","hopping_C","hopping_minusC_realOPAMP"];
ModulesLib = options.ModulesLib ;
PlugIns = options.PlugIns ;
case 'nonH'
ComponentLib  = ["E_A_RC","hopping_L","hopping_AL","hopping_LA","Port_L3","Port_L1"];
ModulesLib = options.ModulesLib ;
PlugIns = options.PlugIns ;
case 'Sigma_SOI'
ComponentLib  = [];
PlugIns = ["Na-(Mb+Lc)","VoltageFollower"];
ModulesLib = [
"Basis_SOI",...
"+sigma_0" ,...
"-sigma_0" ,...
"+isigma_0",...
"-isigma_0",...
"+sigma_1" ,...
"-sigma_1" ,...
"+gen3sigma_2" ,...
"-gen3sigma_2" ,...
"+gen3sigma_3",...
"-gen3sigma_3",...
"+isigma_1_SOI" ,...
"-isigma_1_SOI" ,...
"+igen3sigma_2_SOI" ,...
"-igen3sigma_2_SOI",...
"+igen3sigma_3_SOI",...
"-igen3sigma_3_SOI" ...
];
case 'Chern_M1'
ComponentLib  = [];
PlugIns = ["InvertingOpAmp"];
ModulesLib = [
"Basis_Chern1",...
"+sigma_0" ,...
"-sigma_0" ,...
"+isigma_0",...
"-isigma_0",...
"+sigma_1" ,...
"-sigma_1" ,...
"+gen3sigma_2" ,...
"-gen3sigma_2" ,...
"+gen3sigma_3",...
"-gen3sigma_3",...
"+isigma_1" ,...
"-isigma_1" ,...
"+igen3sigma_2" ,...
"-igen3sigma_2",...
"+igen3sigma_3",...
"-igen3sigma_3" ...
];
case 'Chern_M2'
ComponentLib  = [];
PlugIns = ["IntegratorOpAmp"];
ModulesLib = [
"Basis_Chern2",...
"+sigma_0" ,...
"-sigma_0" ,...
"+isigma_0",...
"-isigma_0",...
"+sigma_1" ,...
"-sigma_1" ,...
"+gen3sigma_2" ,...
"-gen3sigma_2" ,...
"+gen3sigma_3",...
"-gen3sigma_3",...
"+isigma_1" ,...
"-isigma_1" ,...
"+igen3sigma_2" ,...
"-igen3sigma_2",...
"+igen3sigma_3",...
"-igen3sigma_3" ...
];
otherwise
ComponentLib = options.ComponentLib;
ModulesLib = options.ModulesLib ;
PlugIns = options.PlugIns ;
end
fid = fopen(filename,'w');
if ~strcmp(options.OPAMP,'')
fprintf(fid,".inc '%s.LIB'\n' ",options.OPAMP);
end
for PlugIn = PlugIns
Hckt.WritePlugIns(char(PlugIn),fid,magnitude);
end
for Modules = ModulesLib
Hckt.WriteModules(char(Modules),fid,magnitude);
end
for Component = ComponentLib
Hckt.WriteComponent(char(Component),fid,magnitude,options.ErrorMode,options.Error,options.OPAMP);
end
end
